// Kysely table interfaces — the PHYSICAL schema from docs/05_DATA_MODEL.md.
// Money is BIGINT integer cents (ADR-0003): read back as a string (bigint), written as a number.

import type { ColumnType, Generated } from "kysely";

/** bigint cents: SELECT yields a string; INSERT/UPDATE take a number. */
type IntCents = ColumnType<string, number, number>;
/** date column: only ever written (as 'YYYY-MM-DD'). */
type DateOnly = ColumnType<string, string, string>;

export interface DB {
  households: HouseholdsTable;
  accounts: AccountsTable;
  envelopes: EnvelopesTable;
  transfers: TransfersTable;
  envelope_transfers: EnvelopeTransfersTable;
  transactions: TransactionsTable;
  allocations: AllocationsTable;
  templates: TemplatesTable;
  template_lines: TemplateLinesTable;
  recurring_transactions: RecurringTransactionsTable;
  recurring_lines: RecurringLinesTable;
  v_account_balances: AccountBalancesView;
  v_envelope_balances: EnvelopeBalancesView;
}

interface HouseholdsTable {
  id: Generated<string>;
  name: string;
  created_at: Generated<Date>;
}

interface AccountsTable {
  id: Generated<string>;
  household_id: string;
  name: string;
  kind: string;
  created_at: Generated<Date>;
  archived_at: Date | null;
}

interface EnvelopesTable {
  id: Generated<string>;
  household_id: string;
  name: string;
  kind: string;
  created_at: Generated<Date>;
  archived_at: Date | null;
}

/** Account↔account transfer parent (ADR-0004): links its two `kind:'transfer'` legs. */
interface TransfersTable {
  id: Generated<string>;
  household_id: string;
  occurred_on: DateOnly;
  memo: string | null;
  created_at: Generated<Date>;
}

/** Envelope↔envelope reallocation (ADR-0004 B): re-budget money, no account movement. */
interface EnvelopeTransfersTable {
  id: Generated<string>;
  household_id: string;
  from_envelope_id: string;
  to_envelope_id: string;
  amount_cents: IntCents;
  occurred_on: DateOnly;
  memo: string | null;
  created_at: Generated<Date>;
}

interface TransactionsTable {
  id: Generated<string>;
  household_id: string;
  account_id: string;
  amount_cents: IntCents;
  kind: string;
  occurred_on: DateOnly;
  payee: string | null;
  memo: string | null;
  /** Set iff kind = 'transfer'; both legs of a transfer share one transfer_id (ADR-0004). */
  transfer_id: string | null;
  /** Set if this transaction was generated by a recurring rule (FEAT-009); kept on rule delete. */
  recurring_id: string | null;
  created_at: Generated<Date>;
}

interface AllocationsTable {
  id: Generated<string>;
  transaction_id: string;
  envelope_id: string;
  amount_cents: IntCents;
}

interface TemplatesTable {
  id: Generated<string>;
  household_id: string;
  name: string;
  created_at: Generated<Date>;
}

interface TemplateLinesTable {
  id: Generated<string>;
  template_id: string;
  envelope_id: string;
  amount_cents: IntCents;
  position: number;
}

/** Recurring rule (FEAT-009): a template transaction + schedule cursor. */
interface RecurringTransactionsTable {
  id: Generated<string>;
  household_id: string;
  account_id: string;
  direction: string; // 'deposit' | 'withdrawal'
  amount_cents: IntCents; // positive magnitude
  payee: string | null;
  memo: string | null;
  frequency: string; // 'weekly' | 'biweekly' | 'monthly'
  anchor_on: DateOnly;
  next_occurrence_on: ColumnType<string, string, string>;
  created_at: Generated<Date>;
}

interface RecurringLinesTable {
  id: Generated<string>;
  recurring_id: string;
  envelope_id: string;
  amount_cents: IntCents; // positive magnitude
  refund: ColumnType<boolean, boolean | undefined, boolean>;
  position: number;
}

interface AccountBalancesView {
  account_id: string;
  balance_cents: string;
}

interface EnvelopeBalancesView {
  envelope_id: string;
  balance_cents: string;
}
