#!/usr/bin/env bash
# ============================================================================
# demo-instance.sh — run the showcase box (BUD-S93)
#
# A second budgeteer container off the SAME image and tag as the real
# deployment, with its own database, its own secrets, and a published demo
# credential — so the app can be handed to someone, screenshotted, or demoed
# live with the household's real ledger nowhere near it.
#
#   ./scripts/demo-instance.sh up        # start it and load the demo data
#   ./scripts/demo-instance.sh refresh   # re-pristine it between showings
#   ./scripts/demo-instance.sh status    # where it is, and how to get in
#   ./scripts/demo-instance.sh down      # stop it (--purge also drops the data)
#
# Runbook and rationale: docs/DEPLOY_CONTRACT.md §10. Stack: deploy/compose.demo.yaml.
#
# Shell rather than the repo's usual tsx scripts, matching validate-deploy.sh:
# this drives docker/compose and must run on a box that need not have the
# toolchain installed — except for `seed`, which is the one step that does (see
# SEEDING below).
#
# SEEDING — why this is not self-contained. `seedDemo` is deliberately absent
# from the production image (apps/api/scripts/build.ts), which is what keeps
# demo data out of a real deployment entirely rather than merely guarded. So
# the seed runs from THIS repo checkout against the demo database over a
# loopback-published port. `reset`, `reset-password` and the server are all in
# the image, so everything except reseeding works without the toolchain.
# ============================================================================
set -euo pipefail

cd "$(dirname "$0")/.."

COMPOSE_FILE="deploy/compose.demo.yaml"
# Overridable so scripts/validate-demo.sh can drive THIS script — not a copy of it — against
# its own throwaway secrets and ports, without going near the operator's demo box. Nothing
# else should set it; an operator always wants deploy/.env.demo.
ENV_FILE="${BUDGETEER_DEMO_ENV_FILE:-deploy/.env.demo}"

# The published demo credential. Documented, not invented per run: a showing that begins by
# reading a freshly generated password off a terminal is not a demo you can hand to someone,
# and this account guards nothing — the box holds invented data and has its own database.
# Mirrored in DEPLOY_CONTRACT.md §10; change it in both places.
DEMO_USERNAME="demo"
DEMO_PASSWORD="demo-budgeteer"

compose() { docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"; }

fail() { echo "ERROR: $*" >&2; exit 1; }

# Read a value back out of the env file rather than sourcing it — the file holds secrets, and
# sourcing would also let a stray line in it redefine anything in this script.
env_value() { # env_value <KEY> <default>
  local v
  v="$(grep -E "^$1=" "$ENV_FILE" 2>/dev/null | tail -n 1 | cut -d= -f2-)" || true
  echo "${v:-$2}"
}

app_port() { env_value BUDGETEER_DEMO_PORT 3010; }
db_port() { env_value BUDGETEER_DEMO_DB_PORT 5434; }
base_url() { echo "http://127.0.0.1:$(app_port)"; }

# ── init ────────────────────────────────────────────────────────────────────
# Secrets are generated ONCE and kept, not regenerated per run: the database password has to
# keep matching the volume that was initialized with it, and a new SESSION_SECRET would
# invalidate the session of whoever is mid-demo. The file is gitignored (`.env.*`).
cmd_init() {
  if [ -f "$ENV_FILE" ]; then
    echo "$ENV_FILE already exists — keeping it."
    return
  fi
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/demo-instance.sh — NEVER COMMIT (gitignored via .env.*).
# Secrets for the DEMO instance only. The real deployment uses its own, separate values.
DEMO_POSTGRES_PASSWORD=$(openssl rand -hex 16)
DEMO_SESSION_SECRET=$(openssl rand -base64 48)

# Host ports. 3001/5173 are the dev stack, 3002/5174 the cold-start e2e stack, 3099 the
# deploy validation harness — the demo box stays out of all of their lanes.
BUDGETEER_DEMO_PORT=3010
BUDGETEER_DEMO_DB_PORT=5434

# The image to run. Defaults to the same GHCR image and tag as the real deployment.
# BUDGETEER_IMAGE=ghcr.io/wes-cutting/budgeteer:latest
EOF
  echo "Wrote $ENV_FILE (secrets generated, mode 600, gitignored)."
}

require_env() { [ -f "$ENV_FILE" ] || cmd_init; }

wait_for_health() {
  local url="$(base_url)/api/health"
  for _ in $(seq 1 60); do
    if [ "$(curl -s -o /dev/null -w '%{http_code}' "$url" 2>/dev/null)" = "200" ]; then
      return 0
    fi
    sleep 2
  done
  compose logs app
  fail "the demo box never became ready at $url"
}

# ── the demo credential ─────────────────────────────────────────────────────
# Two paths, because a demo box is not always fresh. On a new volume nobody exists, so
# first-run setup creates the account (the same browser-facing endpoint BUD-S92 added). On a
# box that has already been shown, the account exists and may have had its password changed
# by whoever was holding it — so reset it, which also revokes their sessions.
ensure_credential() {
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' -X POST "$(base_url)/api/auth/setup" \
    -H 'content-type: application/json' \
    -d "$(printf '{"username":"%s","password":"%s"}' "$DEMO_USERNAME" "$DEMO_PASSWORD")")"
  case "$code" in
    201)
      echo "Created the demo account \"$DEMO_USERNAME\" via first-run setup."
      ;;
    409)
      compose exec -T \
        -e RESET_USERNAME="$DEMO_USERNAME" -e RESET_PASSWORD="$DEMO_PASSWORD" \
        app node apps/api/dist/cli/reset-password.js >/dev/null
      echo "Restored the demo password for \"$DEMO_USERNAME\"; any live sessions were revoked."
      ;;
    *)
      fail "first-run setup answered $code — expected 201 (new box) or 409 (already set up)"
      ;;
  esac
}

# ── seeding ─────────────────────────────────────────────────────────────────
# Runs from this checkout against the demo database over its loopback port. DATABASE_URL is
# built here from the demo env file and exported for this command only, so nothing about the
# operator's own .env (which may point at a real store) is consulted — process env wins over
# dotenv, which loads the repo .env without overriding.
seed_demo_data() {
  command -v npm >/dev/null || fail "seeding needs npm — see SEEDING at the top of this script"
  [ -d node_modules ] || fail "run 'npm install' first — seeding runs from this checkout"

  local pw url
  pw="$(env_value DEMO_POSTGRES_PASSWORD "")"
  [ -n "$pw" ] || fail "no DEMO_POSTGRES_PASSWORD in $ENV_FILE"
  url="postgres://budgeteer:${pw}@127.0.0.1:$(db_port)/budgeteer"

  echo "--- loading the synthetic demo dataset ---"
  # DATABASE_URL wins unconditionally in createDb(), so a PGLITE_DIR in the operator's .env
  # cannot divert this into a local dev store.
  DATABASE_URL="$url" npm run seed:demo --workspace @budgeteer/api
}

# `seed:demo` refuses any store that already holds ledger data (it is a seeder, not an
# importer), so re-pristining empties the ledger first. `reset` runs INSIDE the container —
# against DATABASE_URL it truncates the ledger and preserves households/users/sessions
# (BUD-S90), which is why the demo account survives a refresh.
reset_ledger() {
  echo "--- emptying the demo ledger ---"
  compose exec -T app node apps/api/dist/db/reset.js >/dev/null
}

# ── commands ────────────────────────────────────────────────────────────────
cmd_up() {
  require_env
  echo "--- starting the demo stack (project: budgeteer-demo) ---"
  compose up -d
  wait_for_health
  ensure_credential
  seed_demo_data
  cmd_status
}

cmd_refresh() {
  require_env
  compose up -d >/dev/null
  wait_for_health
  reset_ledger
  seed_demo_data
  ensure_credential
  echo
  echo "Demo box re-pristined — same URL, same credential, a fresh dataset."
  cmd_status
}

cmd_seed() {
  require_env
  wait_for_health
  seed_demo_data
}

cmd_status() {
  require_env
  local health
  health="$(curl -s "$(base_url)/api/health" 2>/dev/null || echo '(unreachable)')"
  cat <<EOF

  Demo instance
    URL       $(base_url)      (LAN: http://<this-host>:$(app_port))
    Sign in   $DEMO_USERNAME / $DEMO_PASSWORD
    Health    $health
    Data      strictly synthetic (seed:demo) — no real ledger data, ever
    Reset     ./scripts/demo-instance.sh refresh

EOF
}

cmd_down() {
  require_env
  if [ "${1:-}" = "--purge" ]; then
    # Scoped to this compose file, whose project name is pinned to budgeteer-demo — so this
    # can only ever drop the demo volume.
    compose down --volumes --remove-orphans
    echo "Demo stack and its database volume removed."
  else
    compose down --remove-orphans
    echo "Demo stack stopped; its data volume was kept. Use --purge to drop it too."
  fi
}

case "${1:-}" in
  init) cmd_init ;;
  up) cmd_up ;;
  seed) cmd_seed ;;
  refresh) cmd_refresh ;;
  status) cmd_status ;;
  down) shift; cmd_down "$@" ;;
  *)
    cat >&2 <<EOF
Usage: ./scripts/demo-instance.sh <command>

  init      generate deploy/.env.demo (secrets, gitignored) — implied by the rest
  up        start the demo box, ensure the demo credential, load the demo data
  seed      (re)load the synthetic demo dataset
  refresh   re-pristine between showings: empty the ledger, reseed, restore the password
  status    URL, credential, and health
  down      stop it (add --purge to drop the database volume too)

Runbook: docs/DEPLOY_CONTRACT.md §10
EOF
    exit 1
    ;;
esac
